FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# 新台語運動

[新台語運動](https://g0v.hackpad.com/moed7ct-taigi-neologism)
是提供一母語學習網路媒介。

# Group 資料列表

## 顯示列表 [/列表/外語請教條{?%E7%AC%AC%E5%B9%BE%E9%A0%81}]

+ Parameters
    + %E7%AC%AC%E5%B9%BE%E9%A0%81 (optional, number, `1`) ... 顯示第幾頁的列表
    
### GET
列出目前的外語請教條，每頁最多15筆。

+ 列表 (array[string]) - 本頁的外語請教條項目列陣   
+ 列表.外語請教條項目編號 (number)
+ 列表.外語語言 (string)
+ 列表.種類 (string) - "字詞"或"語句"
+ 列表.外語資料 (string)

+ Response 200 (application/json)

        {
          "列表": [
            {
              "外語請教條項目編號": "47765",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "鬱歲"
            },
          ]
        }

## 找特定項目 [/揣/外語請教條{?%E9%97%9C%E9%8D%B5%E5%AD%97}]

+ Parameters
    + %E9%97%9C%E9%8D%B5%E5%AD%97 (string, `漂亮`) ... 要搜尋的關鍵字
    
### GET
+ Response 200 (application/json)

        {
          "資料": [
            {
              "外語請教條項目編號": "37991",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "漂亮"
            }
          ],
          "其他建議": [
            {
              "外語請教條項目編號": "37998",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "漂漂亮亮"
            },
            {
              "外語請教條項目編號": "34267",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "愛漂亮"
            }
          ]
        }

# Group 看資料
看資料的內容，其中資料詳細內容和來源內容有另外做api。

## 看項目以及其相關項目內容 [/資料/內容{?%E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F}]

+ Parameters
    + %E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F (number, `1`)
        要查的項目編號
    
### GET
待改
+ Response 200 (application/json)

        {
          "外語請教條項目編號": "47765",
          "外語語言": "華語",
          "新詞文本": [
            {
              "文本資料": "鬱歲",
              "屬性內容": {
                "音標": "ut-huè/ut-hè"
              },
              "來源": 2,
              "新詞文本項目編號": "47766",
              "收錄者": 1,
              "收錄時間": "2015-04-13 22:04:54"
            }
          ],
          "收錄者": 1,
          "新詞影音": [],
          "語言腔口": "閩南語",
          "外語資料": "鬱歲",
          "收錄時間": "2015-04-13 22:04:54"
        }

## 看資料項目的詳細內容 [/資料/詳細內容{?%E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F}]

+ Parameters
    + %E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F (number, `1`) 
         要查的項目編號

### GET
+ Response 200 (application/json)

        {
            "收錄者": "10",
            "來源":"11",
            "收錄時間":"2015-05-07 13:47:47",
            "種類":"字詞",
            "語言腔口":"閩南語",
            "版權":"會使公開",
            "著作所在地":"花蓮",
            "著作年":"2014",
            "屬性內容":{"詞性":"形容詞", "字數":"2"},
            "推薦用字":"否"
        }
        
## 看收錄者、來源的詳細內容 [/來源/內容{?%E4%BE%86%E6%BA%90%E7%B7%A8%E8%99%9F}]

+ Parameters
    + %E4%BE%86%E6%BA%90%E7%B7%A8%E8%99%9F (number, `1`) 
         要查的收錄者、來源編號

### GET
+ Response 200 (application/json)

        {
            "名":"鄉民",
            "屬性內容":{"出世年":"1950", "出世地":"臺灣", "使用者資料": "有", },
            "email":"sui2@pigu.tw",
            "分數":0
        }
        
# Group POST操作
POST的之前，必須先取得csrf的參數。
<!--csrfmiddlewaretoken=nTboUYpC4kTHnOKTZthmqElf74ZL5DTJ-->

## 取得主機csrf [/看csrf]
### GET
+ Response 200 (application/json)

        {
          "csrftoken": "YNojHNaWlKN40iV9O0iyNBfZFkRw3laW"
        }

# Group 登入登出
目前綁定FB

## 登入 [/accounts/facebook/login/{?next}]

需要先登入，而且需要傳csrf的參數。

+ Parameters
    + next (string, `/`)
        登入完要前往的網頁網址

### GET
+ Response 302 (text/html)

## 登出 [/accounts/logout/{?next}]

+ Parameters
    + next (string, `/`)
        登出後要前往的網頁網址

### POST
+ Response 302 (text/html)

# Group 加資料

需要先登入，而且需要傳csrf的參數。

## 加外語請教條 [/加資料/外語請教條{?%E4%BE%86%E6%BA%90,%E7%A8%AE%E9%A1%9E,%E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3,%E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0,%E8%91%97%E4%BD%9C%E5%B9%B4,%E5%B1%AC%E6%80%A7,%E5%A4%96%E8%AA%9E%E8%AA%9E%E8%A8%80,%E5%A4%96%E8%AA%9E%E8%B3%87%E6%96%99}]

+ Parameters
    + %E4%BE%86%E6%BA%90 (string, `'{"名": "阿媠", "職業": "學生"}'`)
        要先轉成字串。一定要有「名」，其餘資訊視情況增加
    + %E7%A8%AE%E9%A1%9E (string, `字詞`)
        資料的種類：「字詞」、「語句」、…
    + %E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3 (string, `閩南語`)
        不設限，隨意增加語言
    + %E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0 (string, `花蓮`)
        不設限，隨意增加
    + %E8%91%97%E4%BD%9C%E5%B9%B4 (string, `2014`)
        不設限，隨意增加
    + %E5%B1%AC%E6%80%A7 (string, `'{"字數": "2", "詞性": "形容詞"}'`)
        json要先轉成字串。內容不設限，隨意增減
    + %E5%A4%96%E8%AA%9E%E8%AA%9E%E8%A8%80 (string, `華語`)
        不設限，隨意增加
    + %E5%A4%96%E8%AA%9E%E8%B3%87%E6%96%99 (string, `漂亮`)
        不設限，隨意增加

### POST
+ Response 200 (application/json)

        {
            '結果': '成功',
            '平臺項目編號':'1',
        }

## 加新詞影音 [/加資料/新詞影音{?%E4%BE%86%E6%BA%90,%E7%A8%AE%E9%A1%9E,%E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3,%E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0,%E8%91%97%E4%BD%9C%E5%B9%B4,%E5%B1%AC%E6%80%A7,%E5%BD%B1%E9%9F%B3%E8%B3%87%E6%96%99}]

+ Parameters
    + %E4%BE%86%E6%BA%90 (string, `'{"名": "阿媠", "職業": "學生"}'`)
        要先轉成字串。一定要有「名」，其餘資訊視情況增加
    + %E7%A8%AE%E9%A1%9E (string, `字詞`)
        資料的種類：「字詞」、「語句」、…
    + %E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3 (string, `閩南語`)
        不設限，隨意增加語言
    + %E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0 (string, `花蓮`)
        不設限，隨意增加
    + %E8%91%97%E4%BD%9C%E5%B9%B4 (string, `2014`)
        不設限，隨意增加
    + %E5%B1%AC%E6%80%A7 (string, `'{"字數": "2", "詞性": "形容詞"}'`)
        json要先轉成字串。內容不設限，隨意增減
    + %E5%BD%B1%E9%9F%B3%E8%B3%87%E6%96%99 (file)
        不設限，隨意增加

### POST
+ Response 200 (application/json)

        {
            '結果': '成功',
            '平臺項目編號':'2',
        }

## 加新詞文本 [/加資料/新詞文本{?%E4%BE%86%E6%BA%90,%E7%A8%AE%E9%A1%9E,%E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3,%E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0,%E8%91%97%E4%BD%9C%E5%B9%B4,%E5%B1%AC%E6%80%A7,%E6%96%87%E6%9C%AC%E8%B3%87%E6%96%99}]

+ Parameters
    + %E4%BE%86%E6%BA%90 (string, `'{"名": "阿媠", "職業": "學生"}'`)
        要先轉成字串。一定要有「名」，其餘資訊視情況增加
    + %E7%A8%AE%E9%A1%9E (string, `字詞`)
        資料的種類：「字詞」、「語句」、…
    + %E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3 (string, `閩南語`)
        不設限，隨意增加語言
    + %E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0 (string, `花蓮`)
        不設限，隨意增加
    + %E8%91%97%E4%BD%9C%E5%B9%B4 (string, `2014`)
        不設限，隨意增加
    + %E5%B1%AC%E6%80%A7 (string, `'{"字數": "2", "詞性": "形容詞"}'`)
        json要先轉成字串。內容不設限，隨意增減
    + %E6%96%87%E6%9C%AC%E8%B3%87%E6%96%99 (string, `媠`)
        不設限，隨意增加

### POST
+ Response 200 (application/json)

        {
            '結果': '成功',
            '平臺項目編號':'3',
        }

## 加外語新詞文本 [/加資料/外語新詞文本{?%E4%BE%86%E6%BA%90,%E7%A8%AE%E9%A1%9E,%E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3,%E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0,%E8%91%97%E4%BD%9C%E5%B9%B4,%E5%B1%AC%E6%80%A7,%E6%96%87%E6%9C%AC%E8%B3%87%E6%96%99}]

+ Parameters
    + %E4%BE%86%E6%BA%90 (string, `'{"名": "阿媠", "職業": "學生"}'`)
        要先轉成字串。一定要有「名」，其餘資訊視情況增加
    + %E7%A8%AE%E9%A1%9E (string, `字詞`)
        資料的種類：「字詞」、「語句」、…
    + %E8%AA%9E%E8%A8%80%E8%85%94%E5%8F%A3 (string, `閩南語`)
        不設限，隨意增加語言
    + %E8%91%97%E4%BD%9C%E6%89%80%E5%9C%A8%E5%9C%B0 (string, `花蓮`)
        不設限，隨意增加
    + %E8%91%97%E4%BD%9C%E5%B9%B4 (string, `2014`)
        不設限，隨意增加
    + %E5%B1%AC%E6%80%A7 (string, `'{"字數": "2", "詞性": "形容詞"}'`)
        json要先轉成字串。內容不設限，隨意增減
    + %E6%96%87%E6%9C%AC%E8%B3%87%E6%96%99 (string, `媠`)
        不設限，隨意增加

### POST
+ Response 200 (application/json)

        {
            '結果': '成功',
            '平臺項目編號':'4',
        }


# Group 互動操作
需要先登入，而且需要傳csrf的參數。
## 設定推薦用字 [/資料/設定推薦用字{?%E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F}]

+ Parameters
    + %E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F (number, `1`) 
         要設定的項目編號

### POST
+ Response 200 (application/json)

        {
            '結果':'成功'
        }

## 取消推薦用字 [/資料/取消推薦用字{?%E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F}]

+ Parameters
    + %E5%B9%B3%E8%87%BA%E9%A0%85%E7%9B%AE%E7%B7%A8%E8%99%9F (number, `1`) 
         要取消的項目編號

### POST
+ Response 200 (application/json)

        {
            '結果':'成功'
        }
