# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0004_版權加會使公開'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='平臺項目表',
            name='是資料源頭',
        ),
    ]
