# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0005_remove_平臺項目表_是資料源頭'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='使用者表',
            name='分數',
        ),
        migrations.RemoveField(
            model_name='使用者表',
            name='維護團隊',
        ),
    ]
