# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:19
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    正規化sheet表 = apps.get_model("臺灣言語平臺", "正規化sheet表")
    正規化sheet表.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0006_remove_使用者表_維護團隊佮分數'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='正規化sheet表',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='正規化sheet表',
            name='private_key',
        ),
        migrations.AddField(
            model_name='正規化sheet表',
            name='key_file_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
