# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0007_正規化sheet表直接使用key_file_name建立登入憑證'),
    ]

    operations = [
        migrations.AddField(
            model_name='平臺項目表',
            name='按呢無好',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='平臺項目表',
            name='按呢講好',
            field=models.IntegerField(default=0),
        ),
    ]
