# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0008_按呢講好不好欄位'),
    ]

    operations = [
        migrations.AlterField(
            model_name='正規化sheet表',
            name='key_file_name',
            field=models.CharField(max_length=200),
        ),
    ]
