# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0009_key_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='平臺項目表',
            name='愛藏起來',
            field=models.BooleanField(default=False),
        ),
    ]
