# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0010_愛藏起來欄位'),
    ]

    operations = [
        migrations.AddField(
            model_name='平臺項目表',
            name='保存時間',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
