# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0006_delete_資料類型表'),
        ('臺灣言語平臺', '0011_平臺項目表_保存時間'),
    ]

    operations = [
        migrations.CreateModel(
            name='外語請教條',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('臺灣言語資料庫.外語表',),
        ),
    ]
