# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0012_外語請教條'),
    ]

    operations = [
        migrations.AddField(
            model_name='平臺項目表',
            name='查幾擺',
            field=models.IntegerField(default=1),
        ),
    ]
