# Generated by Django 2.1.7 on 2019-02-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0015_使用者表_來源換id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='使用者表',
            old_name='舊來源',
            new_name='來源',
        ),
    ]
