# Generated by Django 2.1.7 on 2019-02-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0015_舊來源表khok資料'),
    ]

    operations = [
        migrations.AlterField(
            model_name='使用者表',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='使用者表',
            name='來源',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='使用者', to='臺灣言語資料庫.來源表'),
        ),
    ]
