# Generated by Django 2.1.7 on 2019-02-23 10:07

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations
from django.db.models.query_utils import Q


def forwards_func(apps, schema_editor):
    外語表 = apps.get_model("臺灣言語資料庫", "外語表")
    華語表 = apps.get_model("臺灣言語平臺", "華語表")
    tsuanpoo=[]
    for 外語 in (
        外語表.objects
        .exclude(
            Q(翻譯文本__文本__平臺項目__推薦用字=True) |
            Q(翻譯文本__文本__文本校對__新文本__平臺項目__推薦用字=True)
        )
        .select_related('平臺項目')
        .distinct()
    ):
        try:
            tsuanpoo.append(華語表(使用者華語=外語.外語資料,新舊=外語.平臺項目.查幾擺))
        except ObjectDoesNotExist:
            tsuanpoo.append(華語表(使用者華語=外語.外語資料,新舊=1))
            
    華語表.objects.bulk_create(tsuanpoo)


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0016_使用者表_舊來源換來源'),
    ]

    operations = [
        migrations.RunPython(forwards_func, lambda x:x),
    ]
