# Generated by Django 2.1.7 on 2019-02-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0007_auto_20161121_2017'),
        ('臺灣言語平臺', '0017_華語表_外語表'),
    ]

    operations = [
        migrations.AddField(
            model_name='華台對應表',
            name='舊文本',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='臺灣言語資料庫.文本表'),
        ),
    ]
