# Generated by Django 2.1.7 on 2019-02-23 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0007_auto_20161121_2017'),
        ('臺灣言語平臺', '0018_華台對應表_舊文本'),
    ]

    operations = [
        migrations.AlterField(
            model_name='華台對應表',
            name='上傳時間',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
