# Generated by Django 2.1.7 on 2019-03-01 14:23

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("auth", "User")
    使用者表 = apps.get_model("臺灣言語平臺", "使用者表")
    for 使用者 in 使用者表.objects.all():
        User.objects.create_user(username=使用者.名, email=使用者.email)


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語平臺', '0021_華台對應表_上傳時間自動產生'),
    ]

    operations = [
        migrations.RunPython(forwards_func, lambda x:x),
    ]
